Repository dart-lang/language, pull requests merged in 2020-06, with the labels that each got.

#997 Adjust futureValueType{,Schema} to propagate `dynamic`
  accepted/future-releases/nnbd/feature-specification.md
  resources/type-system/inference.md
Labels: bug, cla: yes, nnbd, specification

#969 Add feature specification of external/abstract variables
  accepted/future-releases/abstract-external-fields/feature-specification.md
Labels: cla: yes

#1003 Batched small updates
  accepted/future-releases/nnbd/feature-specification.md
  resources/type-system/flow-analysis.md
  resources/type-system/inference.md
Labels: cla: yes, nnbd

#975 Change method override inference to use combined member signature
  resources/type-system/inference.md
Labels: cla: yes

#1024 Move Terminating Tokens proposal into /inactive
  inactive/terminating-tokens.md
Labels: cla: yes

#1032 Response to late comments on PR #969
  accepted/future-releases/abstract-external-fields/feature-specification.md
Labels: cla: yes

#1043 Move extension methods folder to 2.7
  accepted/2.7/static-extension-methods/feature-specification.md
  accepted/2.7/static-extension-methods/implementation-plan.md
Labels: cla: yes

#1053 Fix flow analysis handling of write-captured variables in loops and try-blocks.
  resources/type-system/flow-analysis.md
Labels: cla: yes
