Repository dart-lang/language, pull requests merged in 2023-10, with the labels that each got.

#3395 [extension types] Adjust the paragraph about Object members: They do not need special treatment
  accepted/future-releases/extension-types/feature-specification.md
Labels: specification, extension-types

#3425 Update feature-specification.md
  working/macros/feature-specification.md
Labels: autosubmit

#3408 specify the annotation introspection API and constant evaluation API
  working/macros/aspect-macros.md
  working/macros/example/benchmark/src/shared.dart
  working/macros/feature-specification.md
  working/macros/motivation.md
Labels: static-metaprogramming
